// <auto-generated />
using System;
using FastCut.Infra.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FastCut.Infra.Migrations
{
    [DbContext(typeof(FastCutContext))]
    partial class FastCutContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FastCut.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<int>("IdUser");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("FastCut.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime?>("BrithDay");

                    b.Property<string>("Country");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("Phone");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("FastCut.Domain.Entities.RequestService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookingId");

                    b.Property<DateTime>("Created");

                    b.Property<int>("IdServiceEmployee");

                    b.Property<int?>("ServiceEmployeeId");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ServiceEmployeeId");

                    b.ToTable("RequestService");
                });

            modelBuilder.Entity("FastCut.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("Description");

                    b.Property<bool>("Disponivel");

                    b.Property<int?>("EmployeeId");

                    b.Property<string>("Name");

                    b.Property<string>("Price");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("FastCut.Domain.Entities.ServiceEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId");

                    b.Property<int>("IdEmployee");

                    b.Property<int>("IdService");

                    b.Property<int?>("ServiceId");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceEmployee");
                });

            modelBuilder.Entity("FastCut.Domain.Entities.RequestService", b =>
                {
                    b.HasOne("FastCut.Domain.Entities.Booking")
                        .WithMany("RequestServices")
                        .HasForeignKey("BookingId");

                    b.HasOne("FastCut.Domain.Entities.ServiceEmployee", "ServiceEmployee")
                        .WithMany()
                        .HasForeignKey("ServiceEmployeeId");
                });

            modelBuilder.Entity("FastCut.Domain.Entities.Service", b =>
                {
                    b.HasOne("FastCut.Domain.Entities.Employee")
                        .WithMany("Services")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("FastCut.Domain.Entities.ServiceEmployee", b =>
                {
                    b.HasOne("FastCut.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("FastCut.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
